// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220128221121_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            id = new Guid("241b2a74-3963-493c-980c-451079597285"),
                            Description = "Canal dedicado a dotnetcore",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            id = new Guid("ad38c33a-16a5-4e65-9efa-10e45fc8cf1b"),
                            Description = "Canal dedicado a Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            id = new Guid("214ee928-54b9-4ee6-9308-edd2efc46700"),
                            Description = "Canal dedicado a ReactJs",
                            Name = "ReactJs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
